### ISSUE TITLE
c'est toujours http dans la signature des mails de notifications

### ISSUE THREAD

**Issue by brunob** [seenthis/hebergement#1]

**Comment by brunob** [comment]
huhu @Fil tu m'étonnes que c'est toujours http :p 

https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L54
https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L83
https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L85
https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L130
https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L172
https://github.com/seenthis/seenthis/blob/master/inc/seenthis_notifier.php#L173

**Comment by Fil** [comment]
Hé ho t'es pas payé pour me troller !

**Comment by brunob** [comment]
:*
