### ISSUE TITLE
certains avatars réduits ont un cadre blanc

### ISSUE THREAD

**Issue by Fil** [seenthis/hebergement#10]
c'est le cas actuellement pour intempestive et stephane ; sur l'ancien hébergement je crois qu'il y avait eu le même souci mais je ne me souviens plus de la soluce…
![capture d ecran 2016-07-04 11 39 28](https://cloud.githubusercontent.com/assets/7001/16556754/03b9006a-41dc-11e6-8ced-a37a668c6e67.png)

**Comment by brunob** [comment]
@Fil peut-être un changement dans la conf de spip sur la lib utilisée pour la génération des vignettes ?

**Comment by Fil** [comment]
https://seenthis.net/messages/372622

**Comment by brunob** [comment]
Pour info, on a basculé la génération des vignettes de seenthis de GD vers convert cf seenthis/seenthis_squelettes#174, peut-être que cela corrige aussi le bug signalé ici ?

**Comment by brunob** [comment]
Ça me semble bon maintenant, on ferme :)
