### ISSUE TITLE
la page /tags ne marche pas

### ISSUE THREAD

**Issue by Fil** [seenthis/hebergement#13]
https://seenthis.net/messages/507078

(possible que je me trompe dans mon analyse, mais à priori c'est un pb de htaccess qui ne route pas cet URL comme il faudrait)

**Comment by brunob** [comment]
Voilà qui semble corriger le bug : 

https://github.com/seenthis/hebergement/wiki/Configuration-nginx/_compare/b9897233d4629cdde57d324c760a74701923f44f...f5772793c97b78d5ffcd92a957150e6a5514a8c0

Avant de fermer le ticket, il reste à vérifier que ça ne pète pas les autres variantes de tags/ (mot_fin et mot_flou). Ça semble bon d'après mes essais.

**Comment by Fil** [comment]
tout bon pour moi aussi
