### ISSUE TITLE
Installer SNMP ?

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/hebergement#15]
Ça serait cool d'installer SNMP sur seenthis et de pouvoir ainsi grapher le trafic (j'utilise Cacti).

Je suis volontaire pour faire le travail, mais pas tout de suite, je demande d'abord pour voir s'il y a des objections, remarques, etc.

**Comment by brunob** [comment]
@bortzmeyer je crois que @tech-nova a déjà installé quelques outils de monitoring, il devrait pouvoir t'en dire plus que moi...

**Comment by brunob** [comment]
@tech-nova tu peux nous rappeler quels outils de monitoring tu as mis en place et s'il faut que @bortzmeyer installe ceux qu'ils recommande ?

**Comment by brunob** [comment]
Pour info, on est en train de brancher la nouvelle machine sur un grapheur munin hébergé chez @kent1D.

**Comment by kent1D** [comment]
@brunob il me faudrait un ou plusieurs couples user / pass pour le htaccess

à priori c'est bon de mon coté mais pas du vôtre

**Comment by brunob** [comment]
@kent1D je te file un login/pass pour l'équipe de seenthis en privé.

J'ajoute les règles nécessaires à iptables pour laisser passer ta machine, et merci :)

**Comment by brunob** [comment]
@biggrizzly la machine de @kent1D n'arrive pas à se connecter au serveur sur le port 4949 malgré l'ajout que j'ai effectué à iptable. Tu sais ce qui pourrait bloquer sur ce point ?

**Comment by biggrizzly** [comment]
Hello, 

vi /etc/network/if-up.d/00_firewall

iptables -A INPUT -s 195.154.194.29 -j ACCEPT # Munin/Kent1

sh /etc/network/if-up.d/00_firewall

Et ça doit faire le job. Tu avais limité à tcp... C'est ce qui pose souci à mon avis.

  ----- Original Message -----

**Comment by brunob** [comment]
Nickel, merci @biggrizzly :)

**Comment by brunob** [comment]
Voilà, c'est en place, j'ai partagé l'accès au munin avec les membres de l'équipe tech.

Avant de fermer le ticket, quelques questions : 

@tech-nova souhaites-tu rester dans l'équipe en question ? Veux-tu un accès au munin ?
@bortzmeyer souhaites-tu entrer dans l'équipe en question ? Veux-tu un accès au munin ?

**Comment by brunob** [comment]
Je viens d'activer les plugins munin pour monitorer nginx, mais pour qu'ils fonctionnent il faut d'abord ajouter les règles suivantes dans un des fichiers de conf : 

```
location /nginx_status {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
}
```

Mais comme je ne connais pas du tout nginx, je vous laisse choisir où coller ça :p

**Comment by brunob** [comment]
Et voilà, on a des graphes pour nginx ! 

J'ai du adapter la conf à notre environnement, en ajoutant ce qui suit dans `/etc/nginx/sites-enabled/seenthis` : 

```
  location /nginx_status {
	stub_status on;
	access_log   off;
	allow 217.182.178.243;
	deny all;
  }
```

Dans la définition du host seenthis car notre host default fait un redirect 301 de tout ce qu'il reçoit vers seenthis en https. J'ai aussi du utiliser l'ip de la machine dans la règle allow, car 127.0.01 ou 127.0.1.1 ne fonctionnaient pas.

Puis, il a fallu personnaliser l'url appelée par les plugins munin dans `/etc/munin/plugin-conf.d/munin-node` avec l'ajout suivant : 

```
[nginx*]
env.url https://seenthis.net/nginx_status
```

**Comment by brunob** [comment]
On ferme :)
