### ISSUE TITLE
Version du kernel

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/hebergement#16]
SeenThis tourne avec une version fort ancienne du noyau Linux ( 2.6.32). Je suppose que les seenthisiens ne sont pas adeptes d'installer tout de suite le dernier gadget ou la dernière version de tout. Mais ce qui m'inquiète, ce sont les failles de sécurité, qui ont été très nombreuses dans le noyau Linux, ces dernières années.

Le noyau est apparemment fourni par Online (je ne le trouve pas sur le disque, en tout cas). Quelle est la politique d'Online sur les corerctions des vieux noyaux ? Intègrent-ils les corrections de failles de sécurité ? Et, si non, peut-on changer de noyau facilement ?

**Comment by tech-nova** [comment]
Bonjour les techos,

Le kernel est en fait celui de l'hyerviseur, Proxmox en version 3, qui
effectue effectivement des mises à jour de sécurité.

Pour avoir un kernel plus récent, voici les options :
1) monter de version de l'hyperviseur, en utilisant Proxmox 4 (mais on
n'est plus en openvz, donc on perd en perf
http://www.tomshardware.fr/articles/virtualisation-serveur-hyperviseur-gratuit-logiciels,2-9.html
)
2) prendre un vps dédié à seenthis.net chez un hébergeur quelconque. Le
problème c'est qui va payer ? L'installation sur mon serveur dédié me
permet de noyer la consommation de ressources avec celles de mes autres
clients que j'héberge. Donc ça ne coûte "rien".
3) Abandonner Proxmox au profit de vmware ESX6. OVH fournit une
distribution toute prête :
https://www.ovh.com/fr/serveurs_dedies/distributions/esxi_6.xml.
Ces solutions ne sont pas à l'ordre du jour de mon côté.. Avis aux amateurs
éclairés pour les étudier si nécessaire.

.Gilles

2016-09-14 17:24 GMT+02:00 Stéphane Bortzmeyer notifications@github.com:

**Comment by brunob** [comment]
@bortzmeyer la nouvelle machine utilise `3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux`, est-ce que ça suffit pou fermer le ticket ? :)

**Comment by brunob** [comment]
Comme je le disais, on est passé du kernel  2.6.32 à 3.16.0, on peut fermer.
