### ISSUE TITLE
Expiration du certificat

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/hebergement#17]
Il expire dans dix jours. Comme c'est un Let's Encrypt, je suppose qu'il sera renouvelé automatiquement. Mais comment être sûr ? À partir de quelle date s'inquiéter ?

**Comment by Fil** [comment]
Il faut s'inquiéter tout de suite et demander à @tech-nova de nous rassurer :)

**Comment by brunob** [comment]
Je pense que c'est bon, cf : 

```
cat /etc/cron.d/letsencrypt 
30 2 * * 1 /opt/letsencrypt/letsencrypt-auto renew >> /var/log/le-renew.log
35 2 * * 1 /etc/init.d/nginx reload
```

**Comment by bortzmeyer** [comment]
Donc, cette nuit, le certificat va être renouvelé ? (Ou bien il attendra le dernier moment, le week-end prochain, ce qui me semble casse-gueule.)

PS :  /var/log/le-renew.log n'existe pas, ce qui m'interpelle. Il y a un /var/log/letsencrypt/letsencrypt.log qui contient des message sun peu effrayants :+1: 

```
2016-09-13 23:18:29,983:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 346, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 91, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 237, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 70, in get_authorizations
    resp = self._solve_challenges()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/standalone.py", line 217, in perform
    "At least one of the (possibly) required ports is "
MisconfigurationError: At least one of the (possibly) required ports is already taken.

2016-09-13 23:18:29,985:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 584, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 363, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
```

**Comment by brunob** [comment]
Arf @tech-nova a utilisé certbot, du coup il faudrait qu'il y jette un oeil car perso je ne connais pas l'outil, je préfère utiliser https://github.com/lukas2511/dehydrated

**Comment by brunob** [comment]
@bortzmeyer les erreurs que tu mentionnes semblent provenir du domaine epoxit et d'après ce que j'ai pu trouver d'infos pertinentes parmi la soupe de logs, il semble que ça ce soit bien passé pour les domaines de seenthis.

**Comment by brunob** [comment]
De mieux en mieux, /opt/letsencrypt/ n'existe pas ^^ Je laisse vraiment @tech-nova nous expliquer ce qu'il en est :)

**Comment by tech-nova** [comment]
Bon, clairement ce script est lié à l'ancienne installation. Donc
effectivement il n'est plus à jour. Epoxit n'est plus sur le serveur, je
vais le virer de la liste des certificats à renouveler. Enfin, le
certificat a bien été renouvelé mais il faut faire une opération manuelle
pour qu'il soit pris en compte par le service haproxy.

Je propose de mettre en place pour la suite le script qui automatise tout
cela
https://gist.github.com/T0MM0R/8503d077c5e30030fe41af514bbde9c9

**Comment by bortzmeyer** [comment]
Tiens, le certificat vient d'être renouvelé.

**Comment by tech-nova** [comment]
oui.
https://www.ssllabs.com/ssltest/analyze.html?d=seenthis.net

**Comment by brunob** [comment]
@tech-nova on en est où sur ce point ? Tu as mis en place le script que tu citais ?

**Comment by bortzmeyer** [comment]
Le certificat va expirer dans quatre jours. C'est court. Est-ce qu'il va être remplacé automatiquement ?

**Comment by brunob** [comment]
@tech-nova nous en dira peut-être plus...

**Comment by tech-nova** [comment]
il y a un script qui tourne 2 fois par jour pour mettre à jour les certifs.

**Comment by brunob** [comment]
Super, on peut fermer le ticket alors :)

**Comment by bortzmeyer** [comment]
Euh, mais le script renouvelle le certificat quand ? Là, il reste seulement deux jours, cela me parait imprudent d'attendre le dernier moment !

**Comment by brunob** [comment]
...

**Comment by Fil** [comment]
bon voilà c'est mort … je cherche si c'est documenté quelque part

**Comment by Fil** [comment]
```
root@seenthis:/var/www/seenthis.net/public_html# letsencrypt renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/seen.li.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/static2.seenthis.net.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/static1.seenthis.net.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/seenthis.net.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/static3.seenthis.net.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/seen.li/fullchain.pem (skipped)
  /etc/letsencrypt/live/static2.seenthis.net/fullchain.pem (skipped)
  /etc/letsencrypt/live/static1.seenthis.net/fullchain.pem (skipped)
  /etc/letsencrypt/live/seenthis.net/fullchain.pem (skipped)
  /etc/letsencrypt/live/static3.seenthis.net/fullchain.pem (skipped)
No renewals were attempted.
```

si c'est ça le script, il se trompe…

**Comment by Fil** [comment]
apparemment la doc de la commande `letsencrypt` est là
https://github.com/certbot/certbot

**Comment by Fil** [comment]
bon j'ai une piste : certbot voit que le certificat 6 est bon et ne veut pas le renouveler. Mais quand je cherche le certificat reçu par mon client web, c'est le certificat 5 qui est envoyé !

```
grep -rl V1LK8 /etc/letsencrypt/
/etc/letsencrypt/archive/seenthis.net/fullchain5.pem
/etc/letsencrypt/archive/seenthis.net/cert5.pem
```

donc quelque part le certificat renouvellé est là depuis le 18 nov, mais n'est pas pris en compte.

**Comment by Fil** [comment]
les mauvais certificats sont dans `/etc/haproxy/cert`

**Comment by Fil** [comment]
bon j'ai réussi en découvrant à tâtons le fonctionnement de letsencrypt et de haproxy

la "recette" suivante a permis de solutionner : 

```
# cd /etc/letsencrypt/live
# for i in * ; do cat "$i/"*pem > /etc/haproxy/cert/$i.pem; done
# /etc/init.d/haproxy restart
```

au final le script `letsencrypt renew` ne se trompe pas, mais il ignore qu'il doit reconfigurer haproxy ; il faut probablement ajouter un plugin.

**Comment by tech-nova** [comment]
ok, c'est donc simple.
Le cron actuel met à jour les certificats dans un espace qui n'est pas
accessible au proxy.
Il faut donc écrire un script qui se charge de combiner les certificats
quand c'est nécessaire

C'est expliqué ici, par exemple :
https://gist.githubusercontent.com/thisismitch/7c91e9b2b63f837a0c4b/raw/700cfe953e5d5e71e528baf20337198195606630/le-renew-haproxy
(source :
https://www.digitalocean.com/community/tutorials/how-to-secure-haproxy-with-let-s-encrypt-on-ubuntu-14-04
)

Il ne semble pas être nécessaire de redémarrer le proxy.



On Sat, Dec 17, 2016 at 10:38 PM, Philippe Rivière <notifications@github.com

**Comment by Fil** [comment]
Ce que j'ai fait a permis de décoincer, mais apparemment ce n'est pas parfait, car il y a quelques remarques sur https://www.ssllabs.com/ssltest/analyze.html?d=seenthis.net

- `Chain issues: Incorrect order, Extra certs`
- seen.li tout pourri

**Comment by brunob** [comment]
@tech-nova tu peux t'occuper de ça du coup ?

**Comment by tech-nova** [comment]
Le certificat de letsencrypt apparaissait plusieurs fois dans le fichier
résultat de la concaténation du certificat + clé. J'ai nettoyé. Maintenant
l'erreur n'apparait plus et on est en A+ sur ssllabs.com

**Comment by Fil** [comment]
merci !

**Comment by brunob** [comment]
Tout est réglé ? On peut fermer le ticket ?

**Comment by bortzmeyer** [comment]
@brunob Faudrait peut-être attendre le prochain renouvellement, pour voir ce qu'il se passe...

**Comment by brunob** [comment]
@bortzmeyer ok, je te laisse faire ça une fois que tu penses que c'est bon :)

**Comment by bortzmeyer** [comment]
Expiration dans quatre jours. On va voir ce que cela donne...

**Comment by Fil** [comment]
Si on ne fait rien, dans 4 jours ça va encore foirer :  

```
root@seenthis:/home/fil# ls -al  /etc/haproxy/cert/seenthis.net.pem
-rw------- 1 root root 7053 déc.  18 18:39 /etc/haproxy/cert/seenthis.net.pem
root@seenthis:/home/fil# ls -altr /etc/letsencrypt/live/seenthis.net/
total 8
drwx------ 7 root root 4096 déc.  18 12:25 ..
lrwxrwxrwx 1 root root   39 janv. 17 00:01 privkey.pem -> ../../archive/seenthis.net/privkey7.pem
lrwxrwxrwx 1 root root   41 janv. 17 00:01 fullchain.pem -> ../../archive/seenthis.net/fullchain7.pem
lrwxrwxrwx 1 root root   37 janv. 17 00:01 chain.pem -> ../../archive/seenthis.net/chain7.pem
lrwxrwxrwx 1 root root   36 janv. 17 00:01 cert.pem -> ../../archive/seenthis.net/cert7.pem
drwxr-xr-x 2 root root 4096 janv. 17 00:01 .
```

certbot marche bien et a bien renouvelé les éléments dans /etc/letsencrypt/, mais les nouvelles valeurs n'ont pas été transposées dans les /etc/haproxy/cert/*.pem

**Comment by brunob** [comment]
ping @tech-nova :\

**Comment by Fil** [comment]
La partie manquante de notre affaire est celle-ci :  
```
for i in /etc/letsencrypt/live/*/fullchain.pem; do  domain=$(basename $(dirname "$i")); cat "/etc/letsencrypt/live/$domain/fullchain.pem" "/etc/letsencrypt/live/$domain/privkey.pem" > "/etc/haproxy/certs/$domain.pem"; done
```

Je rajoute cette phrase dans un script `/root/certbot2haproxy` et je l'ajoute à `/etc/cron.d/certbot`. J'ajoute aussi `/etc/init.d/haproxy reload` car il ne suffit apparemment pas de changer le certificat, il faut aussi recharger la config.

**Comment by Fil** [comment]
je suis pas sûr que mon cron marche, à vérifier … mais j'ai lancé le script à la main donc on est OK jusqu'à la prochaine fois : 17 avril 2017.

**Comment by bortzmeyer** [comment]
Le certificat expire dans deux jours, et pas de signe de renouvellement.

**Comment by tech-nova** [comment]
Il a été renouvelé le 17/03,  et expire lr 16/06


Le 14 avr. 2017 3:08 AM, "Stéphane Bortzmeyer" <notifications@github.com> a
écrit :

**Comment by brunob** [comment]
Espérons qu'on pourra fermer ce ticket après le changement d'hébergement sur lequel je propose de m'occuper du bouzin en suivant la méthode que j'utilise toujours cf https://technique.arscenic.org/ssl-securisation-des-communications-serveur-client/article/installer-et-configurer-un-certificat-let-s-encrypt

**Comment by Fil** [comment]
@bortzmeyer qu'est-ce qui te fait dire ça ?

Pour ma part c matin je vois la même chose que @tech-nova : sur le serveur on a bien dans `/etc/haproxy/cert/seenthis.net.pem` une copie de `/etc/letsencrypt/live/seenthis.net/cert.pem` (et ses copains), qui se trouve être un lien symbolique vers la génération 8 `/etc/letsencrypt/archive/seenthis.net/cert8.pem`, valide jusqu'au 16 mai.

Et c'est bien propagé jusqu'au client
<img width="737" alt="capture d ecran 2017-04-14 a 10 31 26" src="https://cloud.githubusercontent.com/assets/7001/25038224/d99eb6b0-20fd-11e7-9b02-d190017f1ff6.png">

**Comment by Fil** [comment]
Confirmé par https://www.ssllabs.com/ssltest/analyze.html?d=seen.li on est A+ sur seen.li et seenthis.net ; pour moi, à moins qu'il y ait eu besoin d'une opération manuelle depuis le message de Stéphane, on peut fermer.

**Comment by tech-nova** [comment]
C'est bon, le crontab avait bien fait son travail

On Fri, Apr 14, 2017 at 10:45 AM, Philippe Rivière <notifications@github.com

**Comment by bortzmeyer** [comment]
@fil Réparé le 14 avril à 06:44 UTC. 

[ 1/5 ] OK - Certificate 'seen.li' will expire on Thu 15 Jun 2017 10:59:00 PM GMT +0000.
NOTIFICATION

Dernier message d'alarme le 14 avril à 01:10 UTC.
	
[icingaadmin] CRITICAL - Certificate 'seen.li' expires in 2 day(s) (Sun 16 Apr 2017 10:00:00 PM GMT +0000).

**Comment by brunob** [comment]
Depuis le changement de machine, on est passé à B d'après https://www.ssllabs.com/ssltest/analyze.html?d=seenthis.net 

On pourrait facilement améliorer ça en virant certains items de `SSLCipherSuite` , perso j'obtiens un A+ avec la conf suivante : 
 `SSLCipherSuite ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS`

**Comment by brunob** [comment]
Pour contourner certbot/certbot#374, j'ai appliqué certbot/certbot#4551 cf : 

```sh
cd /etc/letsencrypt/
openssl dhparam -out dh2048.pem 2048
```

et ajouté ce qui suit dans `seenthis.net/conf/nginx/security.conf` :

```
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
  ssl_dhparam /etc/letsencrypt/dh2048.pem;
```

Sources : https://weakdh.org/sysadmin.html & https://cipherli.st/

Et hop :)

![hop](https://cloud.githubusercontent.com/assets/418064/26561597/eb707064-44bf-11e7-9cd2-2f75443d35a2.png)

**Comment by brunob** [comment]
Je viens d'ajouter un `include /var/www/seenthis.net/conf/nginx/security.conf;` dans `/etc/nginx/sites-enabled/seen.li.conf` afin de bénéficier du fix précédent sur seen.li, et hop : 

![re](https://cloud.githubusercontent.com/assets/418064/26580605/19dec364-4539-11e7-94d8-7f22d30b5112.png)

Attendons la période du renouvellement du domaine (sur ce point je fais pleinement confiance à @biggrizzly), et on devrait enfin pouvoir fermer ce ticket :)

**Comment by brunob** [comment]
Pour en finir avec ce ticket, on pourra le fermer si le certificat est bien renouvelé automatiquement avant le 7 novembre 2017.

**Comment by brunob** [comment]
Le certificat semble bien avoir été renouvelé cf : 

```
Valid from | Sun, 15 Oct 2017 07:30:42 UTC
Valid until | Sat, 13 Jan 2018 07:30:42 UTC (expires in 2 months and 8 days)
```

![certif](https://user-images.githubusercontent.com/418064/32404475-7851e474-c150-11e7-8440-3cd4a8aeacd2.png)

On ferme :)

**Comment by bortzmeyer** [comment]
Moins de trois jours avant l'expiration. À surveiller.

**Comment by Fil** [comment]
Le fait qu'il ne reste que trois jours est un bug en soi, non ?

dans la crontab de `root` on a:
```
# renew letsencrypt certs
30 10 15 * * /opt/letsencrypt/certbot-auto renew
```
je lance la commande à la main : 
```
root@seenthis:/var/www/seenthis.net/public_html# /opt/letsencrypt/certbot-auto renew
Upgrading certbot-auto 0.21.1 to 0.22.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/stdev.zoo-logique.org.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/seenthis.net.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/stdev.zoo-logique.org/fullchain.pem expires on 2018-05-16 (skipped)
  /etc/letsencrypt/live/seenthis.net/fullchain.pem expires on 2018-05-16 (skipped)
No renewals were attempted.
-------------------------------------------------------------------------------
```

donc comme la dernière fois, on a un certificat récent, mais il n'est semble-t-il pas pris en compte par nginx

**Comment by Fil** [comment]
avant/après

<img width="762" alt="avant" src="https://user-images.githubusercontent.com/7001/37256257-50d862a8-2558-11e8-9c06-058a5fe62c0d.png">
<img width="762" alt="apres" src="https://user-images.githubusercontent.com/7001/37256259-52a38cf2-2558-11e8-85b9-c7d4280b76ca.png">


J'ai simplement fait `/etc/init/d/nginx reload` : ce serveur ne plante pas assez souvent !

**Comment by bortzmeyer** [comment]
Icinga est heureux :  

```
==> web-cert on web-seenthis is OK! <==

Info:    OK - Certificate 'seenthis.net' will expire on Wed 16 May 2018 08:30:47
+AM GMT +0000.

When:    2018-03-11 17:16:17 +0000
Service: web-cert (Display Name: "web-cert")
IPv4:    seenthis.net
```

**Comment by bortzmeyer** [comment]
Morale : il ne suffit pas de renouveller le certificat, il faut aussi redémarrer le serveur HTTP.

**Comment by brunob** [comment]
D'après ce post, il faudrait modifier l'appel dans le cron de cette manière : 

`/opt/letsencrypt/certbot-auto renew --renew-hook "service nginx reload"` ou `--post-hook="service nginx reload"`

https://community.letsencrypt.org/t/help-with-cronjob-to-auto-renew-cert-on-nginx/39898/2

Mais bon, je n'y connais pas grand chose à certbot, je lui préfère dehydrated.

**Comment by biggrizzly** [comment]
Hello,

1) Je ne surveille pas la machine ST dans ma supervision, c'est pas bien, merci Stéphane pour ton alerte !
2) Oui, on a oublié le reload, c'est pas bien (bis) Oui, la machine est trop stable... Je vois que le crontab a été modifié. Merci :-)

Bonne soirée !

  ----- Original Message -----
