### ISSUE TITLE
seen.li => seenthis.net

### ISSUE THREAD

**Issue by brunob** [seenthis/hebergement#2]
https://seen.li/ devrait pointer vers https://seenthis.net/

**Comment by tech-nova** [comment]
Je vérifie la config nginx

**Comment by tech-nova** [comment]
corrigé, c'était un ordre dans les règles de redirection

Voici /etc/nginx/conf.d/seen.li.conf

```
server {
    listen 80;
    server_name seen.li;
    return 301 https://seen.li$request_uri;
}

server {
#   listen 80;
    listen 8080;
    server_name seen.li;

    location / {
        rewrite ^/(.+)$   https://seenthis.net/index.php?action=seenli&me=$1  permanent;
        rewrite ^ https://seenthis.net/ permanent;
   }
}
```

**Comment by brunob** [comment]
Super, j'ai reporté les fichiers de conf dans une page du wiki https://github.com/seenthis/hebergement/wiki/Configuration-nginx

On ferme :)
