### ISSUE TITLE
Migration de seenthis : détail de la procédure, des tests en amont, etc..

### ISSUE THREAD

**Issue by tech-nova** [seenthis/hebergement#20]
Salut les seenthisien.ne.s,

J'ouvre ce sujet pour qu'on définisse précisément les éléments à mettre en place pour une transition sans effet de bord ni coupure.

Quelques points de base : 

- On peut partir de la structure actuelle ou remettre à plat la configuration (conseillée)
- Il est possible de migrer une IP /32 du serveur actuel vers un Public Cloud OVH, cela peut faciliter la transition.
- On peut en amont de la migration des fichiers commencer par une migration de la base de données vers un serveur externe pour qu'il n'y ait aucune interruption lors du changement de serveur
- On peut rediriger via iptable tout le trafic d'un serveur à l'autre, ce qui permet de ne pas avoir de coupure (liée à un changement d'IP) si les fichiers ont été synchronisés juste avant.
- etc..

A nous d'écrire précisément le scénario que l'on va mettre en place pour ne rien oublier et être certain que tout se passera bien.

Avez-vous des expériences précises dans ce domaine ?

**Comment by brunob** [comment]
Salut, maintenant que la migration a eu lieu, on peut fermer le ticket ? Ou alors on poste un petit compte rendu de la méthode utilisée dans une page du wiki ? @biggrizzly ton avis ?

**Comment by brunob** [comment]
Pas de nouvelle, on ferme :)
