### ISSUE TITLE
Les nouveaux seens n'apparaissent pas

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/hebergement#24]
Suite à la panne d'aujourd'hui, les nouveaux seens (écrits via l'API) n'apparaissent pas. L'API n'indique pas d'erreur mais le seen semble perdu dans un trou noir.

**Comment by bortzmeyer** [comment]
Deux seens ainsi disparus, un avec une vidéo YouTube sur une ampoule connectée et un sur le sous-marin nucléaire Suffren.

**Comment by brunob** [comment]
Est-ce que cela passait depuis dimanche ? Cette question car on a fait un upgrade du site en SPIP 3.2 dans l'après midi de samedi 6 juillet pour les 10 ans de seenthis.

Possible que le bug provienne de la surcharge que le serveur a subi à cause de ce bug https://github.com/seenthis/seenthis_squelettes/issues/214

**Comment by bortzmeyer** [comment]
La dernière fois que j'avais testé, c'était il y a une semaine. https://seenthis.net/messages/791186 Là, les deux seens ne sont toujours pas apparus, donc ce n'est pas un problème de surcharge temporaire.

**Comment by rastapopougros** [comment]
Bé ça peut être temporaire si, puisque s'ils ont été envoyé pendant que c'était planté, ça n'aurait jamais répondu, et donc effectivement perdu dans le néant à jamais. Du coup ils n'auraient aucun raison de réapparaitre plus tard.

**Comment by brunob** [comment]
Je pense qu'on peut fermer ce ticket, ce repo sert à discuter de l'hébergement, s'il y a un bug ou une amélioration à apporter dans l'API , c'est sur le repo principal qu'il faut en discuter :)

**Comment by bortzmeyer** [comment]
@brunob Lequel ? https://github.com/seenthis/seenthis n'autorise pas pas la création de tickets.

**Comment by brunob** [comment]
@bortzmeyer par ici https://github.com/seenthis/seenthis_squelettes ;)
