### ISSUE TITLE
[URGENT] L'API ne fonctionne plus (tous les seens sont perdus)

### ISSUE THREAD

**Issue by bortzmeyer** [seenthis/hebergement#25]
#24 a été fermé à tort donc j'ouvre un nouveau ticket. Depuis la dernière panne, l'API de création ne fonctionne plus, elle répond OK mais les seens sont perdus. (J'ai encore sssayé il y a cinq minutes.)

**Comment by bortzmeyer** [comment]
Également mis en https://github.com/seenthis/seenthis_squelettes/issues/218

**Comment by brunob** [comment]
Merci pour le déplacement du ticket, je ferme celui-ci.
