### ISSUE TITLE
installation du répertoire squelettes 

### ISSUE THREAD

**Issue by Fil** [seenthis/hebergement#26]
J'ai fait une màj suite à seenthis/seenthis_squelettes#229, mais le répertoire plugins/seenthis_squelettes/ était quand même bien vieux (ça m'a pullé plein de modifs), bref je sais pas si j'ai bien fait de svn up.

Et surtout, pourquoi c'est svn et pas git ? Il faudrait certainement nettoyer un peu tout ça :)

**Comment by brunob** [comment]
J'ai donc basculé tous les plugins seenthis en git sauf `seenthis_sphinx` qui contient des modifications locales (c'est pas bien), je vous laisse y remédier et me signaler quand c'est fait pour qu'on puisse lui aussi le basculer en git.

**Comment by brunob** [comment]
Remarque : bon, par contre on ne pourra plus faire `svn up plugins/*` :\

**Comment by brunob** [comment]
Pour info, avant que j'annule brutalement les modifications locales de `seenthis_sphinx` : 

```diff
Index: cli_indexer.php
===================================================================
--- cli_indexer.php	(revision 31)
+++ cli_indexer.php	(working copy)
@@ -4,6 +4,7 @@
   die('ce script ne fonctionne qu\'en ligne de commande');
 
 define('_CLI_', true);
+define('_HTTPS', 'https'); ## seenthis
 
 date_default_timezone_set('Europe/Paris');
 
@@ -13,8 +14,12 @@
 chdir(dirname(__FILE__));
 
 chdir('../..');
+
+echo "hum…\n";
 require_once 'ecrire/inc_version.php';
 
+echo "OK\n";
+
 spip_timer('indexer');
 
 include_spip('indexer_sphinx');
Index: sphinx2.html
===================================================================
--- sphinx2.html	(revision 31)
+++ sphinx2.html	(working copy)
@@ -201,10 +201,10 @@
 
 	{pagination (#ENV{vue}|?{100,20})}
 >
-	#SET{id,#PROPERTIES|json_decode{1}|table_valeur{id_objet}}
+	#SET{id,#PROPERTIES|table_valeur{id_objet}}
 	<li class='item' id="message#GET{id}">
 	[(#ENV{vue}|oui)
-		[(#SET{prop,[(#PROPERTIES*|json_decode{1})]})]
+		[(#SET{prop,[(#PROPERTIES)]})]
 		<INCLURE{fond=noisettes/sphinxshort,prop=#GET*{prop},valeur=#VALEUR*} />
 	][(#ENV{vue}|non)
 	[<div class="surlignable">

```

**Comment by brunob** [comment]
ping :)

**Comment by rastapopougros** [comment]
Cette modif a dû être faite quand on a tout mis à jour, car #PROPERTIES est déjà décodé en amont désormais. Je ne sais pas à quoi sert ce squelette en particulier, mais ça peut être commité.

**Comment by Fil** [comment]
pas de souvenir précis, go and break things

**Comment by brunob** [comment]
Voilà, les modifs locales de sphinx sont reportées dans le repo et tous les plugins seenthis sont en git sur la prod, on ferme.
