### ISSUE TITLE
vérifier comment fonctionne 7h36

### ISSUE THREAD

**Issue by Fil** [seenthis/hebergement#3]
c'est un cron, mais à priori il tourne encore sur l'ancien serveur…

**Comment by Fil** [comment]
De fait ça marche bien : le cron est sur alan et le rss sur epoxit; mais comme ils sont indépendants ça ne foire pas. Je pourrais déplacer le cron sur epoxit aussi (et le virer sur alan pour ne pas avoir de doublons). À voir… de toutes façons tant que la mailing-liste est sur listes.rezo.net on a besoin des deux machines.

**Comment by brunob** [comment]
bonne nouvelle :)

**Comment by Fil** [comment]
C'est un cron sur alan qui appelle un script dans mon home 

```
# envoi de la newsletter de 7h36
36 07 * * * php /home/fil/7h36/7h36.php 7h36@rezo.net
```
