### ISSUE TITLE
baisser le niveau de log des erreurs php

### ISSUE THREAD

**Issue by brunob** [seenthis/hebergement#6]
SPIP 2.1 génère beaucoup de log d'erreurs PHP passé un certain niveau, perso, avec apache, je baisse le niveau à LogLevel error pour éviter de gaver le disque.

Je ne sais pas où on règle ça sur la machine, mais là on passe notre temps à écrire sur le disque (lancez un tail sur error.log et sortez le popcorn ^^). Même si on a un sdd, ça vaudrait le coup de baisser le niveau.

**Comment by Fil** [comment]
Oui.

Est-ce qu'on peut trouver un script qui échantillonne ce qu'on a déjà
récolté et nous donne les messages d'erreurs par ordre de fréquence,
histoire qu'on puisse aussi régler les erreurs en question ?

-- Fil

**Comment by brunob** [comment]
C'est une mission pour sed ça non ?

**Comment by brunob** [comment]
quelques liens qui devraient être utiles :
- http://strictcoder.blogspot.fr/2012/02/linux-count-unique-error-log-entries.html
- http://unix.stackexchange.com/questions/7789/using-grep-sed-awk-to-classify-log-file-entries 
- http://superuser.com/questions/414343/i-want-to-get-a-count-of-unique-entries-in-the-apache-error-logs-on

Cette commande semble pas mal : 

`sed -n '/PHP /p' error_log | sed 's^\[.*\]^^g' | sed 's^\, referer: [^\n]*^^g' | sort | uniq -c > error_log-unique`

> Here is another variation to only keep errors that contain the string "PHP ". By using the "-n" option in conjunction with the "p" argument, sed will not print out any thing except matching lines. In addition, I've added a sed command to remove the ", referer: ..." that can appear at the end of each line which can vary. By removing the referer, the error logs can be grouped together more precisely.

**Comment by brunob** [comment]
Je viens d'augmenter le niveau de log à crit (il était à error, la valeur par défaut).

`error_log /var/www/seenthis.net/log/error.log crit;` dans `/etc/nginx/conf.d/seenthis.net.conf`

source : http://nginx.org/en/docs/ngx_core_module.html#error_log
