### ISSUE TITLE
l'API ne fonctionne pas

### ISSUE THREAD

**Issue by Fil** [seenthis/hebergement#9]
signalé par stephane: https://seenthis.net/messages/505099#message506276

**Comment by bortzmeyer** [comment]
/messages (voir un URL est enregistré) marchait. Seul /api/messages (créer un nouveau seen) déconnait. En réinstallant mon client local (ah, le packaging Python...), ça remarche (https://seenthis.net/messages/506313) Désolé pour la fausse alerte.

**Comment by brunob** [comment]
merci pour le retour @bortzmeyer, on ferme :)
